### ISSUE TITLE
 ./byfn.sh -m generate has issue when run your sample

### ISSUE THREAD

**Issue by blackwhites** [siyuyifang/balance-transfer-java#1]
root@blockchain:/balance-transfer-java/artifacts# ./byfn.sh -m generate
Generating certs and genesis block for with channel 'mychannel' and CLI timeout of '10' seconds and CLI delay of '3' seconds
Continue (y/n)? y
proceeding ...
/balance-transfer-java/artifacts/bin/cryptogen

##########################################################
##########################################################
./byfn.sh: line 210: /balance-transfer-java/artifacts/bin/cryptogen: cannot execute binary file: Exec format error
Failed to generate certificates...

**Comment by Guppster** [comment]
I can replicate this issue on Ubuntu 16.04.1.  This is occurring because the packaged binaries are for a different system architecture than ours. 
The original balance-transfer example doesn't include these binaries because they are platform-specific and should always be downloaded using the script provided in the official documentation.

Quick Fix:

1.  Get the binaries you need and add them to your PATH: http://hyperledger-fabric.readthedocs.io/en/release-1.1/samples.html#binaries
2. Comment out line 32 in ./artifacts/byfn

I'll submit a PR resolving this soon

**Comment by blackwhites** [comment]
You are right,now I can run it sucessfuly
